# Generated by Django 4.1.13 on 2024-07-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
