# Generated by Django 4.1.13 on 2024-07-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_system', '0002_college_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
